### PR TITLE
Fix/ignore z entities

### PR DESCRIPTION
**Pull request by LoyVanBeek**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Please create an issue for implementation of this in ED instead of this hack.

**Comment by LoyVanBeek** [comment]
You're right: https://github.com/tue-robotics/ed/issues/78

**Comment by MatthijsBurgh** [comment]
@LoyVanBeek status of this PR?

**Comment by LoyVanBeek** [comment]
No work done on ED and to be honest I have no desire to dig into that. Merging this is the fastest way to get it done, unfortunately.

**Comment by MatthijsBurgh** [comment]
Yeo, therefore we createdthe issue. But this PR is ready to be reviewed?

**Comment by LoyVanBeek** [comment]
Yes

**Comment by MatthijsBurgh** [comment]
> *radius might still not be enough. If you just take a max height difference of 2, take Pythagoras, so `radius=sqrt(2`
@LoyVanBeek what do you think about my suggestion for the radius?

**Comment by MatthijsBurgh** [comment]
@LoyVanBeek ping;)

**Pull request merged**
