### PR TITLE
Refactor/entity

### PR DESCRIPTION
**Pull request by jlunenburg**
Linked to https://github.com/tue-robotics/tue_robocup/issues/151

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
There are a bunch of TODO's added that need to be taken care of before merging.

**Comment by LoyVanBeek** [comment]
Also, is there no way to unify Shape and Volume? They're essentially the same thing right?

**Comment by LoyVanBeek** [comment]
R5Cop works, many other challenges as well as far as testable in simulation

**Comment by reinzor** [comment]
First validate on real robot please :)

-Rein

**Comment by LoyVanBeek** [comment]
Validated on real robot with r5cop_demo and that worked OK.

**Pull request merged**
