### PR TITLE
add impuls environment

### PR DESCRIPTION
**Pull request by PetervDooren**
Files were just copied from robotics_testlab environment

### CODE REVIEW

**Comment by PetervDooren** [comment]
The whole robocup knowledge thing is a mess. It combines multiple things that have no business being together such as knowledge about an environement used for reasoning, speech recognition grammar, properties of object catagories and semantic properties of specific furniture.
We need to clean this up at some point because this is not maintainable.

**Comment by MatthijsBurgh** [comment]
Maybe we should start by moving all the common functions to a shared file. Instead of copying them for each env.

**Comment by PetervDooren** [comment]
That is not a step we can make now due to lack of resources (my time). 
I think we should start by thinking this over carefully.

**Comment by LarsJanssenTUe** [comment]
I agree with Peter. I think a redesign can and should be done, before which I don't think it helps to start making these kind of changes. Therefore I will accept this PR, in order to unblock any potential development.

**Review by LarsJanssenTUe — APPROVED** [review]

**Pull request merged**
