### PR TITLE
Store odometer data default in home folder

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
It stores the driven distance
So it will not spam the entire mega folder.

**Comment by PetervDooren** [comment]
What do we use this data for? Is it used by something or could we just as well not store it?

**Comment by MatthijsBurgh** [comment]
I would like to have it so we can put in the annual report, etc.

**Comment by PetervDooren** [comment]
This does not sound like it requires a lot of data. There might be a better way to get those statistics other than spamming a folder with data.
I'll approve the pull request, this is not something we need to look into right now

**Pull request merged**
