### PR TITLE
Use handover detector to detect failed handover

### PR DESCRIPTION
**Pull request by PetervDooren**
Merge after #1326 
Fixes one of the issues in #1325

### CODE REVIEW

**Review by PetervDooren — COMMENTED** [review]
Tested on the robot. Worked like a charm

**Review by MatthijsBurgh — CHANGES_REQUESTED** [review]
I think the issue was always it requires tuning per item it is holding. I think that downside is still there. So works like a charm for a subset of items probably. Please prove me wrong.

**Comment by PetervDooren** [comment]
That subset is all objects that are not paper thin. Which includes at least all objects used in serve breakfast. I tested it with a spoon and bowl

**Review by MatthijsBurgh — CHANGES_REQUESTED** [review]
Add comment about the used tuning for detector works for what set of items, i.e. their dimensions

**Comment by PetervDooren** [comment]
There was no tuning done in this PR. it just uses the grasp detector. Grasp detector is tuned for how accurate it can detect things. No need to add a comment here.

**Comment by MatthijsBurgh** [comment]
There is no comment either in the challenge or the ActiveGraspDetector about which the dimensions is works on. It is only mentioned when the object is too thin/small it doesn't work. No clue about what that threshold is.\

**Comment by PetervDooren** [comment]
Docstring of ActiveGraspDetector states anything wider than the threshold (0.075 rad on the gripper) can be detected. You can say this is not clear enough but that is not an issue for this PR
        
       State for detecting whether the robot is holding something using the gripper position.

        Stores current position of the hand motor joint, slightly closes the gripper and then compares the new
        position with the first one. If the difference is bigger than the threshold, robot is holding something

        If the object is too small/thin it will not be able to determine

        :param robot: Robot to execute the state with
        :param arm_designator: designator that resolves to arm to check
        :param threshold_difference: Difference between base and final position
        :param minimum_position: Minimum position to assume that the gripper is holding something
        :param max_torque: Max torque of the gripper to perform the test with

**Review by MatthijsBurgh — APPROVED** [review]

**Pull request merged**
