### PR TITLE
add python-numpy run dependenncy

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by reinzor** [comment]
Build is failing apparently ... We need to fix this first ..

**Comment by LoyVanBeek** [comment]
The .travis.yaml of this has always been borked. I 'fixed' it multiple times but because it depends on everything, it breaks when anything breaks. 
This new dependency is not making that difference.

**Comment by reinzor** [comment]
I agree but then just work from the ground up to fix everything and not just accept this :)

-Rein

**Comment by LoyVanBeek** [comment]
It's in the works but takes a lot of effort and waiting time and then it breaks for no good reason.

**Pull request merged**
