### PR TITLE
Example test armtojointconfig

### PR DESCRIPTION
**Pull request by shanki98**
I have created an example StateMachine for `ArmToJointConfig` as disccussed. Additionally, I added a checking condition inside the state ArmToJointConfig to return an error if the configuration does not exist. Even though this is a part of `test_die`, which asserts an error.

### CODE REVIEW

**Review by MatthijsBurgh — DISMISSED** [review]

**Comment by PetervDooren** [comment]
Question: did you have the opportunity to test this on the robot yesterday?

**Review by shanki98 — COMMENTED** [review]
I have made changes as per the review @MatthijsBurgh and @PetervDooren

**Comment by shanki98** [comment]
Should this example be tested on the robot before merging into master ?
@PetervDooren 
It works fine on simulation

**Comment by shanki98** [comment]
This has also been tested on the robot

**Review by PetervDooren — APPROVED** [review]

**Pull request merged**
